
import java.util.Random;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */



public class MainFrame extends javax.swing.JFrame {
    
    //variables
    String user, Password;
    String adminUser = "admin";
    String adminPass = "MyPass";
    String customer[] = {"Trevor"};
    String customerPass[] = {"password"};
    boolean logIn;
    Random rand = new Random();
    double n = rand.nextDouble(30.00);
    MainFrame.Customer custArry[] = null;
    MainFrame.custCart cart[] = null;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        
    }
    
    public class Customer
    {
        String newFN, newLN, newAdd, User, password;
        int newCard, coupon;
        
    }
    
    public class Admin
    {
        String newFN, newLN, newAdd, User, password;
        int newCard;
    }
    
    public class custCart
    {
        String foodTitle;
        double cost;
        int discount;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuJframe = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        itemOneCost = new javax.swing.JLabel();
        itemTwo = new javax.swing.JLabel();
        itemOneName = new javax.swing.JLabel();
        homeFromMenu = new javax.swing.JButton();
        cartFromMenu = new javax.swing.JButton();
        userDisplay = new javax.swing.JLabel();
        queue = new javax.swing.JLabel();
        addItemOne = new javax.swing.JButton();
        addItemTwo = new javax.swing.JButton();
        itemTwoCost = new javax.swing.JLabel();
        itemThree = new javax.swing.JLabel();
        itemThreeCost = new javax.swing.JLabel();
        addItemThree = new javax.swing.JButton();
        itemThreeName = new javax.swing.JLabel();
        itemFourName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        itemTwoName = new javax.swing.JLabel();
        itemFourCost = new javax.swing.JLabel();
        addItemFour = new javax.swing.JButton();
        Cart = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        cartDisplay = new javax.swing.JTextArea();
        cartUserDisplay = new javax.swing.JLabel();
        cartQueueDisplay = new javax.swing.JLabel();
        Confirmation = new javax.swing.JFrame();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        CreateAcc = new javax.swing.JFrame();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jFormattedTextField4 = new javax.swing.JFormattedTextField();
        jFormattedTextField5 = new javax.swing.JFormattedTextField();
        jFormattedTextField6 = new javax.swing.JFormattedTextField();
        jFormattedTextField7 = new javax.swing.JFormattedTextField();
        jFormattedTextField8 = new javax.swing.JFormattedTextField();
        jButton7 = new javax.swing.JButton();
        adminMenu = new javax.swing.JFrame();
        menu = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        login = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        passwordInput = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        userNameInput = new javax.swing.JTextField();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BLT.jpg"))); // NOI18N

        itemOneCost.setText("jLabel2");

        itemTwo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lemonchicken.jpg"))); // NOI18N
        itemTwo.setText("jLabel3");

        itemOneName.setText("Bacon Lettuce Tomato");

        homeFromMenu.setText("Home");
        homeFromMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeFromMenuActionPerformed(evt);
            }
        });

        cartFromMenu.setText("Cart");
        cartFromMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartFromMenuActionPerformed(evt);
            }
        });

        userDisplay.setText("jLabel9");

        queue.setText("jLabel10");

        addItemOne.setText("jButton1");
        addItemOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemOneActionPerformed(evt);
            }
        });

        addItemTwo.setText("jButton1");

        itemTwoCost.setText("jLabel2");

        itemThree.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spaghett.jpg"))); // NOI18N
        itemThree.setText("jLabel2");

        itemThreeCost.setText("jLabel3");

        addItemThree.setText("jButton2");

        itemThreeName.setText("jLabel8");

        itemFourName.setText("jLabel2");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prociuttopizza.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");

        itemTwoName.setText("jLabel8");

        itemFourCost.setText("jLabel8");

        addItemFour.setText("jButton1");

        javax.swing.GroupLayout menuJframeLayout = new javax.swing.GroupLayout(menuJframe.getContentPane());
        menuJframe.getContentPane().setLayout(menuJframeLayout);
        menuJframeLayout.setHorizontalGroup(
            menuJframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuJframeLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(menuJframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuJframeLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 240, Short.MAX_VALUE)
                        .addComponent(itemThree, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(236, 236, 236))
                    .addGroup(menuJframeLayout.createSequentialGroup()
                        .addComponent(itemTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(211, 211, 211))
                    .addGroup(menuJframeLayout.createSequentialGroup()
                        .addComponent(itemTwoName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(itemFourName)
                        .addGap(396, 396, 396))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuJframeLayout.createSequentialGroup()
                        .addGroup(menuJframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(menuJframeLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(homeFromMenu)
                                .addGap(28, 28, 28)
                                .addComponent(cartFromMenu))
                            .addGroup(menuJframeLayout.createSequentialGroup()
                                .addGroup(menuJframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(itemOneName)
                                    .addGroup(menuJframeLayout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(itemOneCost)
                                        .addGap(34, 34, 34)
                                        .addComponent(addItemOne)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(itemThreeName)))
                        .addGap(239, 239, 239)
                        .addComponent(userDisplay)
                        .addGap(18, 18, 18)
                        .addComponent(queue)
                        .addGap(59, 59, 59))))
            .addGroup(menuJframeLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(itemTwoCost)
                .addGap(32, 32, 32)
                .addComponent(addItemTwo)
                .addGap(346, 346, 346)
                .addComponent(itemFourCost)
                .addGap(43, 43, 43)
                .addComponent(addItemFour)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuJframeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(itemThreeCost)
                .addGap(27, 27, 27)
                .addComponent(addItemThree)
                .addGap(264, 264, 264))
        );
        menuJframeLayout.setVerticalGroup(
            menuJframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuJframeLayout.createSequentialGroup()
                .addGroup(menuJframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuJframeLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(menuJframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userDisplay)
                            .addComponent(queue)))
                    .addGroup(menuJframeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(menuJframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cartFromMenu)
                            .addComponent(homeFromMenu))))
                .addGap(38, 38, 38)
                .addGroup(menuJframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(menuJframeLayout.createSequentialGroup()
                        .addGroup(menuJframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(itemOneName)
                            .addComponent(itemThreeName))
                        .addGap(18, 18, 18)
                        .addGroup(menuJframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(menuJframeLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(menuJframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(addItemOne)
                                    .addComponent(itemOneCost)))
                            .addComponent(itemThree, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(menuJframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(itemThreeCost)
                            .addComponent(addItemThree))
                        .addGap(43, 43, 43))
                    .addGroup(menuJframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(itemFourName)
                        .addComponent(itemTwoName)))
                .addGap(18, 18, 18)
                .addGroup(menuJframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(menuJframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(itemTwoCost)
                    .addGroup(menuJframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addItemTwo)
                        .addComponent(itemFourCost)
                        .addComponent(addItemFour)))
                .addContainerGap(164, Short.MAX_VALUE))
        );

        cartDisplay.setColumns(20);
        cartDisplay.setRows(5);
        jScrollPane1.setViewportView(cartDisplay);

        cartUserDisplay.setText("cust info");

        cartQueueDisplay.setText("queue display");

        javax.swing.GroupLayout CartLayout = new javax.swing.GroupLayout(Cart.getContentPane());
        Cart.getContentPane().setLayout(CartLayout);
        CartLayout.setHorizontalGroup(
            CartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CartLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(154, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CartLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cartUserDisplay)
                .addGap(33, 33, 33)
                .addComponent(cartQueueDisplay)
                .addGap(27, 27, 27))
        );
        CartLayout.setVerticalGroup(
            CartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CartLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cartUserDisplay)
                    .addComponent(cartQueueDisplay))
                .addGap(61, 61, 61)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(287, Short.MAX_VALUE))
        );

        jTextField4.setText("Confirmed");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ConfirmationLayout = new javax.swing.GroupLayout(Confirmation.getContentPane());
        Confirmation.getContentPane().setLayout(ConfirmationLayout);
        ConfirmationLayout.setHorizontalGroup(
            ConfirmationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConfirmationLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(265, Short.MAX_VALUE))
        );
        ConfirmationLayout.setVerticalGroup(
            ConfirmationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConfirmationLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(330, Short.MAX_VALUE))
        );

        jScrollPane4.setViewportView(jTextPane2);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jTextField8.setText("Firstname");

        jTextField9.setText("Lastname");

        jTextField10.setText("Phone number:");

        jTextField11.setText("Card number");
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });

        jTextField12.setText("Zipcode");

        jTextField13.setText("Username");

        jTextField14.setText("Password");

        jPasswordField1.setText("jPasswordField1");

        jFormattedTextField3.setText("jFormattedTextField3");

        jFormattedTextField4.setText("jFormattedTextField4");

        jFormattedTextField5.setText("jFormattedTextField5");

        jFormattedTextField6.setText("jFormattedTextField6");

        jFormattedTextField7.setText("jFormattedTextField7");

        jFormattedTextField8.setText("jFormattedTextField8");
        jFormattedTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField8ActionPerformed(evt);
            }
        });

        jButton7.setText("Create");

        javax.swing.GroupLayout CreateAccLayout = new javax.swing.GroupLayout(CreateAcc.getContentPane());
        CreateAcc.getContentPane().setLayout(CreateAccLayout);
        CreateAccLayout.setHorizontalGroup(
            CreateAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateAccLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(CreateAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CreateAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(CreateAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(CreateAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CreateAccLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CreateAccLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(CreateAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7))))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        CreateAccLayout.setVerticalGroup(
            CreateAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateAccLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(CreateAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(CreateAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CreateAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CreateAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CreateAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CreateAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CreateAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout adminMenuLayout = new javax.swing.GroupLayout(adminMenu.getContentPane());
        adminMenu.getContentPane().setLayout(adminMenuLayout);
        adminMenuLayout.setHorizontalGroup(
            adminMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        adminMenuLayout.setVerticalGroup(
            adminMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menu.setText("Menu");
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });

        jButton3.setText("Cart");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        login.setText("Log In");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        jButton6.setText("Create Account");

        passwordInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordInputActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/name.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");

        jLabel5.setText("Username");

        jLabel6.setText("Password");

        jLabel7.setText("OR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(271, 271, 271)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(menu)
                        .addGap(31, 31, 31)
                        .addComponent(jButton3)
                        .addGap(272, 272, 272))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(passwordInput, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                .addGap(269, 269, 269))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(userNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton6)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel7))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(menu))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(userNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(16, 16, 16)
                .addComponent(login)
                .addGap(3, 3, 3)
                .addComponent(jLabel7)
                .addGap(26, 26, 26)
                .addComponent(jButton6)
                .addGap(0, 129, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //General sets
    
   
    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        //initialize menu items;
        
        //TODO: WHEN ADMIN MENU IS INITIALLIZED I CAN SET MENU PRICES
        
        this.menuJframe.setVisible(true);
        this.menuJframe.setSize(1000,1000);
        this.dispose();
    }//GEN-LAST:event_menuActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
    
      
      Password = passwordInput.getText();                                       // passes inputted text to Password and user vars
      user = userNameInput.getText();
      
    if(user.equals(adminUser) && Password.equals( adminPass))                   // checks if strings are equal to admin information
    {
        this.adminMenu.setSize(1000,1000);                                        
        this.adminMenu.setVisible(true);
        logIn = true;
        this.dispose();
        
    }
    else                                                                        // this section checks customer array and makes sure customer logins are correct
    {
        for(int i = 0; i < custArry.length; i++)
        {
            if(custArry[i].User.equals(user) && custArry[i].password.equals(Password))
            {
                
                    
                this.menuJframe.setSize(1000,1000);                       // if everything matches customer menu will pop open with customer info
                this.menuJframe.setVisible(true);
                String curUserStr = "Current user: "+ custArry[i].newFN + " "+custArry[i].newLN;
                userDisplay.setText(curUserStr);                        // text box shows current user
                cartUserDisplay.setText(curUserStr);
                String queueStr ="Estimated wait: "+ Queue() + " mins";
                queue.setText(queueStr);                                // text box shows estimated wait time using random number generator in Queue()
                cartQueueDisplay.setText(queueStr);
                logIn = true;                                           // log in boolean for other pages to use
                this.dispose();                                         // close old window
                    
                
            }
            else
            {
                logIn = false;
            }
        }
    }
    }//GEN-LAST:event_loginActionPerformed

    private void jFormattedTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField8ActionPerformed

    private void homeFromMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeFromMenuActionPerformed
        new MainFrame().setVisible(true); 
        this.menuJframe.dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_homeFromMenuActionPerformed

    private void cartFromMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartFromMenuActionPerformed
        this.Cart.setVisible(true);
        this.Cart.setSize(800, 800);
        this.menuJframe.dispose();
    }//GEN-LAST:event_cartFromMenuActionPerformed

    private void passwordInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordInputActionPerformed
       Password = passwordInput.toString();        // TODO add your handling code here:
    }//GEN-LAST:event_passwordInputActionPerformed

    private void addItemOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemOneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addItemOneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }


private double Queue()
{
    for(double i = n; i > 0; i--)
    {
        n = n - 0.0001;
    }
   double num = Math.round(n);
    return num;
}

private void setCustInfo(String FirstName, String LastName, int card, String address, String username, String psswrd)
{
    
    Customer cust = new Customer();
    
    cust.User = username;
    cust.newFN = FirstName;
    cust.newLN = LastName;
    cust.newAdd = address;
    cust.newCard = card;
    cust.password = psswrd;
    
    
    for(int i = 0; i < custArry.length; i++ )
    {
        if(custArry[i] == null)
        {
            custArry[i] = cust;
        }
    }
    
}

private void custCart(String name, double cost, int coupon)
{
      
    custCart newCart = new custCart();
    newCart.foodTitle = name;
    newCart.cost = cost;
    newCart.discount = coupon;
    
    for(int i = 0; i < cart.length; i++)
    {
        if(cart[i] == null)
        {
            cart[i] = newCart;
        }
    }
    
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame Cart;
    private javax.swing.JFrame Confirmation;
    private javax.swing.JFrame CreateAcc;
    private javax.swing.JButton addItemFour;
    private javax.swing.JButton addItemOne;
    private javax.swing.JButton addItemThree;
    private javax.swing.JButton addItemTwo;
    private javax.swing.JFrame adminMenu;
    private javax.swing.JTextArea cartDisplay;
    private javax.swing.JButton cartFromMenu;
    private javax.swing.JLabel cartQueueDisplay;
    private javax.swing.JLabel cartUserDisplay;
    private javax.swing.JButton homeFromMenu;
    private javax.swing.JLabel itemFourCost;
    private javax.swing.JLabel itemFourName;
    private javax.swing.JLabel itemOneCost;
    private javax.swing.JLabel itemOneName;
    private javax.swing.JLabel itemThree;
    private javax.swing.JLabel itemThreeCost;
    private javax.swing.JLabel itemThreeName;
    private javax.swing.JLabel itemTwo;
    private javax.swing.JLabel itemTwoCost;
    private javax.swing.JLabel itemTwoName;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JFormattedTextField jFormattedTextField4;
    private javax.swing.JFormattedTextField jFormattedTextField5;
    private javax.swing.JFormattedTextField jFormattedTextField6;
    private javax.swing.JFormattedTextField jFormattedTextField7;
    private javax.swing.JFormattedTextField jFormattedTextField8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JButton login;
    private javax.swing.JButton menu;
    private javax.swing.JFrame menuJframe;
    private javax.swing.JPasswordField passwordInput;
    private javax.swing.JLabel queue;
    private javax.swing.JLabel userDisplay;
    private javax.swing.JTextField userNameInput;
    // End of variables declaration//GEN-END:variables
}
