
import java.util.Random;
import javax.swing.SwingConstants;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */



public class MainFrame extends javax.swing.JFrame {
    
    //variables
    String user, Password;
    String adminUser = "admin";
    String adminPass = "MyPass";
    String customer[] = {"Trevor"};
    String customerPass[] = {"password"};
    boolean logIn;
    Random rand = new Random();
    double n = rand.nextDouble(30.00);
    MainFrame.Customer custArry[] = null;
    MainFrame.custCart cart[] = null;
    String cartName = "<html>Item Name: <br> Price: </html>";
    
    

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        this.setSize(1000,1000);
        if(cartOneNamePrice.getText().equals("nothing"))
        {
            cartOneNamePrice.setText("Nothing here");
            cartOne.setText( cartName);
            deleteOne.setVisible(false);
        }
        if(cartTwoPriceName.getText().equals("nothing"))
        {
            cartTwoPriceName.setVisible(false);
            cartTwo.setVisible(false);
            deleteTwo.setVisible(false);
        }if(cartThreePriceName.getText().equals("nothing"))
        {
            cartThreePriceName.setVisible(false);
            cartThree.setVisible(false);
            deleteThree.setVisible(false);
        }if(cartFourPriceName.getText().equals("nothing"))
        {
            cartFourPriceName.setVisible(false);
            cartFour.setVisible(false);
            deleteFour.setVisible(false);
        }if(cartFivePriceName.getText().equals("nothing"))
        {
            cartFivePriceName.setVisible(false);
            cartFive.setVisible(false);
            deleteFive.setVisible(false);
        }if(cartSixPriceName.getText().equals("nothing"))
        {
            cartSixPriceName.setVisible(false);
            cartSix.setVisible(false);
            deleteSix.setVisible(false);
        }
        
    }
    
    public class Customer
    {
        String newFN, newLN, newAdd, User, password;
        int newCard, coupon;
        
    }
    
    public class Admin
    {
        String newFN, newLN, newAdd, User, password;
        int newCard;
    }
    
    public class custCart
    {
        String foodTitle;
        double cost;
        int discount;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuJframe = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        itemOneCost = new javax.swing.JLabel();
        itemTwo = new javax.swing.JLabel();
        itemOneName = new javax.swing.JLabel();
        homeFromMenu = new javax.swing.JButton();
        cartFromMenu = new javax.swing.JButton();
        userDisplay = new javax.swing.JLabel();
        queue = new javax.swing.JLabel();
        addItemOne = new javax.swing.JButton();
        addItemTwo = new javax.swing.JButton();
        itemTwoCost = new javax.swing.JLabel();
        itemThree = new javax.swing.JLabel();
        itemThreeCost = new javax.swing.JLabel();
        addItemThree = new javax.swing.JButton();
        itemThreeName = new javax.swing.JLabel();
        itemFourName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        itemTwoName = new javax.swing.JLabel();
        itemFourCost = new javax.swing.JLabel();
        addItemFour = new javax.swing.JButton();
        Cart = new javax.swing.JFrame();
        cartUserDisplay = new javax.swing.JLabel();
        cartQueueDisplay = new javax.swing.JLabel();
        cartOneNamePrice = new javax.swing.JLabel();
        cartOne = new javax.swing.JLabel();
        cartTwo = new javax.swing.JLabel();
        cartTwoPriceName = new javax.swing.JLabel();
        cartThree = new javax.swing.JLabel();
        cartThreePriceName = new javax.swing.JLabel();
        cartSix = new javax.swing.JLabel();
        cartFourPriceName = new javax.swing.JLabel();
        cartFour = new javax.swing.JLabel();
        cartFivePriceName = new javax.swing.JLabel();
        cartFive = new javax.swing.JLabel();
        cartSixPriceName = new javax.swing.JLabel();
        menuFromCart = new javax.swing.JButton();
        Checkout = new javax.swing.JButton();
        deleteOne = new javax.swing.JButton();
        deleteTwo = new javax.swing.JButton();
        deleteThree = new javax.swing.JButton();
        deleteFour = new javax.swing.JButton();
        deleteFive = new javax.swing.JButton();
        deleteSix = new javax.swing.JButton();
        Confirmation = new javax.swing.JFrame();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        CreateAcc = new javax.swing.JFrame();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jFormattedTextField4 = new javax.swing.JFormattedTextField();
        jFormattedTextField5 = new javax.swing.JFormattedTextField();
        jFormattedTextField6 = new javax.swing.JFormattedTextField();
        jFormattedTextField7 = new javax.swing.JFormattedTextField();
        jFormattedTextField8 = new javax.swing.JFormattedTextField();
        jButton7 = new javax.swing.JButton();
        adminMenu = new javax.swing.JFrame();
        checkoutJFrame = new javax.swing.JFrame();
        failedLogIn = new javax.swing.JDialog();
        fail = new javax.swing.JLabel();
        Exit = new javax.swing.JButton();
        menu = new javax.swing.JButton();
        cartFromHome = new javax.swing.JButton();
        login = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        passwordInput = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        userNameInput = new javax.swing.JTextField();

        menuJframe.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BLT.jpg"))); // NOI18N
        menuJframe.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 120, 231, 139));

        itemOneCost.setText("jLabel2");
        menuJframe.getContentPane().add(itemOneCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 281, -1, -1));

        itemTwo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lemonchicken.jpg"))); // NOI18N
        itemTwo.setText("jLabel3");
        menuJframe.getContentPane().add(itemTwo, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 422, 222, 146));

        itemOneName.setText("Bacon Lettuce Tomato");
        menuJframe.getContentPane().add(itemOneName, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 86, -1, -1));

        homeFromMenu.setText("Home");
        homeFromMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeFromMenuActionPerformed(evt);
            }
        });
        menuJframe.getContentPane().add(homeFromMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 13, -1, -1));

        cartFromMenu.setText("Cart");
        cartFromMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartFromMenuActionPerformed(evt);
            }
        });
        menuJframe.getContentPane().add(cartFromMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 13, -1, -1));

        userDisplay.setText("jLabel9");
        menuJframe.getContentPane().add(userDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(798, 32, -1, -1));

        queue.setText("jLabel10");
        menuJframe.getContentPane().add(queue, new org.netbeans.lib.awtextra.AbsoluteConstraints(853, 32, -1, -1));

        addItemOne.setText("Add");
        addItemOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemOneActionPerformed(evt);
            }
        });
        menuJframe.getContentPane().add(addItemOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 277, -1, -1));

        addItemTwo.setText("Add");
        addItemTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemTwoActionPerformed(evt);
            }
        });
        menuJframe.getContentPane().add(addItemTwo, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 590, -1, -1));

        itemTwoCost.setText("jLabel2");
        menuJframe.getContentPane().add(itemTwoCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 590, -1, -1));

        itemThree.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spaghett.jpg"))); // NOI18N
        itemThree.setText("jLabel2");
        menuJframe.getContentPane().add(itemThree, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 120, 197, 194));

        itemThreeCost.setText("jLabel3");
        menuJframe.getContentPane().add(itemThreeCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(572, 336, -1, -1));

        addItemThree.setText("Add");
        addItemThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemThreeActionPerformed(evt);
            }
        });
        menuJframe.getContentPane().add(addItemThree, new org.netbeans.lib.awtextra.AbsoluteConstraints(636, 332, -1, -1));

        itemThreeName.setText("jLabel8");
        menuJframe.getContentPane().add(itemThreeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 86, -1, -1));

        itemFourName.setText("jLabel2");
        menuJframe.getContentPane().add(itemFourName, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 384, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prociuttopizza.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        menuJframe.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 418, 222, 154));

        itemTwoName.setText("jLabel8");
        menuJframe.getContentPane().add(itemTwoName, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 384, -1, -1));

        itemFourCost.setText("jLabel8");
        menuJframe.getContentPane().add(itemFourCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(539, 594, -1, -1));

        addItemFour.setText("Add");
        addItemFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemFourActionPerformed(evt);
            }
        });
        menuJframe.getContentPane().add(addItemFour, new org.netbeans.lib.awtextra.AbsoluteConstraints(619, 590, -1, -1));

        Cart.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cartUserDisplay.setText("Customer");
        Cart.getContentPane().add(cartUserDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, -1));

        cartQueueDisplay.setText("Queue Time");
        Cart.getContentPane().add(cartQueueDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, -1, -1));

        cartOneNamePrice.setText("nothing");
        Cart.getContentPane().add(cartOneNamePrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, -1, -1));

        cartOne.setText("jLabel2");
        Cart.getContentPane().add(cartOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, -1));

        cartTwo.setText("jLabel8");
        Cart.getContentPane().add(cartTwo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, -1, -1));

        cartTwoPriceName.setText("nothing");
        Cart.getContentPane().add(cartTwoPriceName, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, -1, -1));

        cartThree.setText("jLabel10");
        Cart.getContentPane().add(cartThree, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, -1, -1));

        cartThreePriceName.setText("nothing");
        Cart.getContentPane().add(cartThreePriceName, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, -1, -1));

        cartSix.setText("jLabel12");
        Cart.getContentPane().add(cartSix, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, -1, -1));

        cartFourPriceName.setText("nothing");
        Cart.getContentPane().add(cartFourPriceName, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, -1, -1));

        cartFour.setText("jLabel2");
        Cart.getContentPane().add(cartFour, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, -1, -1));

        cartFivePriceName.setText("nothing");
        Cart.getContentPane().add(cartFivePriceName, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, -1, -1));

        cartFive.setText("jLabel10");
        Cart.getContentPane().add(cartFive, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, -1, -1));

        cartSixPriceName.setText("nothing");
        Cart.getContentPane().add(cartSixPriceName, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, -1, -1));

        menuFromCart.setText("Menu");
        menuFromCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFromCartActionPerformed(evt);
            }
        });
        Cart.getContentPane().add(menuFromCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 91, -1));

        Checkout.setText("Checkout");
        Checkout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckoutActionPerformed(evt);
            }
        });
        Cart.getContentPane().add(Checkout, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 91, -1));

        deleteOne.setText("Delete");
        Cart.getContentPane().add(deleteOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, -1, 21));

        deleteTwo.setText("Delete");
        deleteTwo.setPreferredSize(new java.awt.Dimension(60, 21));
        Cart.getContentPane().add(deleteTwo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 65, -1));

        deleteThree.setText("Delete");
        Cart.getContentPane().add(deleteThree, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, -1, 21));

        deleteFour.setText("Delete");
        Cart.getContentPane().add(deleteFour, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, -1, 21));

        deleteFive.setText("Delete");
        Cart.getContentPane().add(deleteFive, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, -1, 21));

        deleteSix.setText("Delete");
        Cart.getContentPane().add(deleteSix, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, -1, 21));

        jTextField4.setText("Confirmed");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ConfirmationLayout = new javax.swing.GroupLayout(Confirmation.getContentPane());
        Confirmation.getContentPane().setLayout(ConfirmationLayout);
        ConfirmationLayout.setHorizontalGroup(
            ConfirmationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConfirmationLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(265, Short.MAX_VALUE))
        );
        ConfirmationLayout.setVerticalGroup(
            ConfirmationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConfirmationLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(330, Short.MAX_VALUE))
        );

        jScrollPane4.setViewportView(jTextPane2);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jTextField8.setText("Firstname");

        jTextField9.setText("Lastname");

        jTextField10.setText("Phone number:");

        jTextField11.setText("Card number");
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });

        jTextField12.setText("Zipcode");

        jTextField13.setText("Username");

        jTextField14.setText("Password");

        jPasswordField1.setText("jPasswordField1");

        jFormattedTextField3.setText("jFormattedTextField3");

        jFormattedTextField4.setText("jFormattedTextField4");

        jFormattedTextField5.setText("jFormattedTextField5");

        jFormattedTextField6.setText("jFormattedTextField6");

        jFormattedTextField7.setText("jFormattedTextField7");

        jFormattedTextField8.setText("jFormattedTextField8");
        jFormattedTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField8ActionPerformed(evt);
            }
        });

        jButton7.setText("Create");

        javax.swing.GroupLayout CreateAccLayout = new javax.swing.GroupLayout(CreateAcc.getContentPane());
        CreateAcc.getContentPane().setLayout(CreateAccLayout);
        CreateAccLayout.setHorizontalGroup(
            CreateAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateAccLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(CreateAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CreateAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(CreateAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(CreateAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CreateAccLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CreateAccLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(CreateAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7))))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        CreateAccLayout.setVerticalGroup(
            CreateAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateAccLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(CreateAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(CreateAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CreateAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CreateAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CreateAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CreateAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CreateAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout adminMenuLayout = new javax.swing.GroupLayout(adminMenu.getContentPane());
        adminMenu.getContentPane().setLayout(adminMenuLayout);
        adminMenuLayout.setHorizontalGroup(
            adminMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        adminMenuLayout.setVerticalGroup(
            adminMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout checkoutJFrameLayout = new javax.swing.GroupLayout(checkoutJFrame.getContentPane());
        checkoutJFrame.getContentPane().setLayout(checkoutJFrameLayout);
        checkoutJFrameLayout.setHorizontalGroup(
            checkoutJFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        checkoutJFrameLayout.setVerticalGroup(
            checkoutJFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        failedLogIn.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fail.setText("Incorrect or missing credentials");
        failedLogIn.getContentPane().add(fail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        Exit.setText("OK");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        failedLogIn.getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 65, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu.setText("Menu");
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 228, -1, -1));

        cartFromHome.setText("Cart");
        cartFromHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartFromHomeActionPerformed(evt);
            }
        });
        getContentPane().add(cartFromHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 228, -1, -1));

        login.setText("Log In");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 400, 86, -1));

        jButton6.setText("Create Account");
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 470, -1, -1));

        passwordInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordInputActionPerformed(evt);
            }
        });
        getContentPane().add(passwordInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 362, 74, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/name.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 27, 418, -1));

        jLabel5.setText("Username");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 325, -1, -1));

        jLabel6.setText("Password");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 365, -1, -1));

        jLabel7.setText("OR");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 438, -1, -1));
        getContentPane().add(userNameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 322, 74, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //General sets
    
   
    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        //initialize menu items;
        
        //TODO: WHEN ADMIN MENU IS INITIALLIZED I CAN SET MENU PRICES
        
        this.menuJframe.setVisible(true);
        this.menuJframe.setSize(1000,1000);
        this.dispose();
    }//GEN-LAST:event_menuActionPerformed

    private void cartFromHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartFromHomeActionPerformed
        this.Cart.setVisible(true);
        this.Cart.setSize(1000, 1000);
        this.dispose();
    }//GEN-LAST:event_cartFromHomeActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
    
      
      Password = passwordInput.getText();                                       // passes inputted text to Password and user vars
      user = userNameInput.getText();
      
    if(user.equals(adminUser) && Password.equals( adminPass))                   // checks if strings are equal to admin information
    {
        this.adminMenu.setSize(1000,1000);                                        
        this.adminMenu.setVisible(true);
        logIn = true;
        this.dispose();
        
    }
    if(user.equals("")|| Password.equals(""))
    {
        failedLogIn.setSize(450,450);
        failedLogIn.setVisible(true);
        failedLogIn.setTitle("Log In Fail");
        fail.setText("Incorrect or missing credentials");
        fail.setVerticalAlignment(SwingConstants.CENTER);
        logIn = false;        
    }
    else                                                                        // this section checks customer array and makes sure customer logins are correct
    {
        for(int i = 0; i < custArry.length; i++)
        {
            if(custArry[i].User.equals(user) && custArry[i].password.equals(Password))
            {
                
                    
                this.menuJframe.setSize(1000,1000);                       // if everything matches customer menu will pop open with customer info
                this.menuJframe.setVisible(true);
                String curUserStr = "Current user: "+ custArry[i].newFN + " "+custArry[i].newLN;
                userDisplay.setText(curUserStr);                        // text box shows current user
                cartUserDisplay.setText(curUserStr);
                String queueStr ="Estimated wait: "+ Queue() + " mins";
                queue.setText(queueStr);                                // text box shows estimated wait time using random number generator in Queue()
                cartQueueDisplay.setText(queueStr);
                logIn = true;                                           // log in boolean for other pages to use
                this.dispose();                                         // close old window
                    
                
            }
            else
            {
                failedLogIn.setSize(500,500);
                failedLogIn.setVisible(true);
                failedLogIn.setTitle("Log In Fail");
                fail.setText("Incorrect or missing credentials");
                fail.setVerticalAlignment(SwingConstants.CENTER);
                logIn = false;
            }
        }
    }
    }//GEN-LAST:event_loginActionPerformed

    private void jFormattedTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField8ActionPerformed

    private void homeFromMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeFromMenuActionPerformed
        new MainFrame().setVisible(true); 
        this.menuJframe.dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_homeFromMenuActionPerformed

    private void cartFromMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartFromMenuActionPerformed
        this.Cart.setVisible(true);
        this.Cart.setSize(1000, 1000);
        this.menuJframe.dispose();
    }//GEN-LAST:event_cartFromMenuActionPerformed

    private void passwordInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordInputActionPerformed
       Password = passwordInput.toString();        // TODO add your handling code here:
    }//GEN-LAST:event_passwordInputActionPerformed

    private void addItemOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemOneActionPerformed
        deleteOne.setVisible(true);
        String cart = "<html>    "+ itemOneName.getText() + "<br>    "+ itemOneCost.getText()+ "</html>";
        cartOneNamePrice.setText(cart);
    }//GEN-LAST:event_addItemOneActionPerformed

    private void addItemTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemTwoActionPerformed
        cartTwoPriceName.setVisible(true);
        deleteTwo.setVisible(true);
        cartTwo.setVisible(true);
        cartTwo.setText(cartName);
        String cart = "<html>     "+ itemTwoName.getText() + "<br>    "+ itemTwoCost.getText()+ "</html>";
        cartTwoPriceName.setText(cart);
    }//GEN-LAST:event_addItemTwoActionPerformed

    private void addItemThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemThreeActionPerformed
        cartThreePriceName.setVisible(true);
        deleteThree.setVisible(true);
        cartThree.setVisible(true);
        cartThree.setText(cartName);
        String cart = "<html>     "+ itemThreeName.getText() + "<br>    "+ itemThreeCost.getText()+ "</html>";
        cartThreePriceName.setText(cart);  
    }//GEN-LAST:event_addItemThreeActionPerformed

    private void addItemFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemFourActionPerformed
        cartFourPriceName.setVisible(true);
        deleteFour.setVisible(true);
        cartFour.setVisible(true);
        cartFour.setText(cartName);
        String cart = "<html>     "+ itemFourName.getText() + "<br>    "+ itemFourCost.getText()+ "</html>";
        cartFourPriceName.setText(cart);
    }//GEN-LAST:event_addItemFourActionPerformed

    private void menuFromCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFromCartActionPerformed
        this.menuJframe.setVisible(true);
        this.menuJframe.setSize(1000,1000);
        this.Cart.dispose();
    }//GEN-LAST:event_menuFromCartActionPerformed

    private void CheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckoutActionPerformed
        this.checkoutJFrame.setVisible(true);
        this.checkoutJFrame.setSize(1000, 1000);
        this.dispose();
    }//GEN-LAST:event_CheckoutActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        failedLogIn.dispose();
    }//GEN-LAST:event_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }


private double Queue()
{
    for(double i = n; i > 0; i--)
    {
        n = n - 0.0001;
    }
   double num = Math.round(n);
    return num;
}

private void setCustInfo(String FirstName, String LastName, int card, String address, String username, String psswrd)
{
    
    Customer cust = new Customer();
    
    cust.User = username;
    cust.newFN = FirstName;
    cust.newLN = LastName;
    cust.newAdd = address;
    cust.newCard = card;
    cust.password = psswrd;
    
    
    for(int i = 0; i < custArry.length; i++ )
    {
        if(custArry[i] == null)
        {
            custArry[i] = cust;
        }
    }
    
}

private void custCart(String name, double cost, int coupon)
{
      
    custCart newCart = new custCart();
    newCart.foodTitle = name;
    newCart.cost = cost;
    newCart.discount = coupon;
    
    for(int i = 0; i < cart.length; i++)
    {
        if(cart[i] == null)
        {
            cart[i] = newCart;
        }
    }
    
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame Cart;
    private javax.swing.JButton Checkout;
    private javax.swing.JFrame Confirmation;
    private javax.swing.JFrame CreateAcc;
    private javax.swing.JButton Exit;
    private javax.swing.JButton addItemFour;
    private javax.swing.JButton addItemOne;
    private javax.swing.JButton addItemThree;
    private javax.swing.JButton addItemTwo;
    private javax.swing.JFrame adminMenu;
    private javax.swing.JLabel cartFive;
    private javax.swing.JLabel cartFivePriceName;
    private javax.swing.JLabel cartFour;
    private javax.swing.JLabel cartFourPriceName;
    private javax.swing.JButton cartFromHome;
    private javax.swing.JButton cartFromMenu;
    private javax.swing.JLabel cartOne;
    private javax.swing.JLabel cartOneNamePrice;
    private javax.swing.JLabel cartQueueDisplay;
    private javax.swing.JLabel cartSix;
    private javax.swing.JLabel cartSixPriceName;
    private javax.swing.JLabel cartThree;
    private javax.swing.JLabel cartThreePriceName;
    private javax.swing.JLabel cartTwo;
    private javax.swing.JLabel cartTwoPriceName;
    private javax.swing.JLabel cartUserDisplay;
    private javax.swing.JFrame checkoutJFrame;
    private javax.swing.JButton deleteFive;
    private javax.swing.JButton deleteFour;
    private javax.swing.JButton deleteOne;
    private javax.swing.JButton deleteSix;
    private javax.swing.JButton deleteThree;
    private javax.swing.JButton deleteTwo;
    private javax.swing.JLabel fail;
    private javax.swing.JDialog failedLogIn;
    private javax.swing.JButton homeFromMenu;
    private javax.swing.JLabel itemFourCost;
    private javax.swing.JLabel itemFourName;
    private javax.swing.JLabel itemOneCost;
    private javax.swing.JLabel itemOneName;
    private javax.swing.JLabel itemThree;
    private javax.swing.JLabel itemThreeCost;
    private javax.swing.JLabel itemThreeName;
    private javax.swing.JLabel itemTwo;
    private javax.swing.JLabel itemTwoCost;
    private javax.swing.JLabel itemTwoName;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JFormattedTextField jFormattedTextField4;
    private javax.swing.JFormattedTextField jFormattedTextField5;
    private javax.swing.JFormattedTextField jFormattedTextField6;
    private javax.swing.JFormattedTextField jFormattedTextField7;
    private javax.swing.JFormattedTextField jFormattedTextField8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JButton login;
    private javax.swing.JButton menu;
    private javax.swing.JButton menuFromCart;
    private javax.swing.JFrame menuJframe;
    private javax.swing.JPasswordField passwordInput;
    private javax.swing.JLabel queue;
    private javax.swing.JLabel userDisplay;
    private javax.swing.JTextField userNameInput;
    // End of variables declaration//GEN-END:variables
}
